site_name: 'sAwMIL: Multiple Instance SVMs'
site_url: https://sawmil.readthedocs.io/
repo_url: https://github.com/carlomarxdk/sawmil
repo_name: carlomarxdk/sawmil
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: false
  - tables
  - footnotes
  - def_list
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - autorefs
  - bibtex:
      bib_file: "refs.bib"
  - mkdocstrings:
      handlers:
        python:
          # Make mkdocstrings import from your repo’s src/ without installing
          paths: [src]
          options:
            show_source: true
            docstring_style: google        # or "numpy" if you standardize on that
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            allow_inspection: true
            parameter_headings: false
            show_root_heading: true      # hide the top "Module" heading
            show_category_heading: false
            show_root_members_full_path: false
            show_symbol_type_toc: true
            show_root_toc_entry: false
            docstring_section_style: list 


  - mkdocs-jupyter:
      execute: false
      include_source: true
      ignore_h1_titles: true
  - section-index

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Examples:
    - Usage: examples.md
    - Jupyter Notebooks: notebooks/example.ipynb
  - Models:
      - SVM: models/svm.md
      - NSK: models/nsk.md
      - sMIL: models/sMIL.md
      - sAwMIL: models/sAwMIL.md
  - API Reference: api.md
  - Citation: citation.md
