name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Tests (py${{ matrix.python }} • ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latests]
        python: ["3.11", "3.12", "3.13", "3.13.7"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Upgrade pip & build tooling
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build wheel setuptools

      - name: Install project with OSQP (dev)
        run: |
          # Installs runtime + dev tools + OSQP path (SciPy pulled via extra)
          pip install -e ".[dev,osqp]"

      - name: Run tests
        run: pytest -q
        env:
          PYTHONWARNINGS: default

  build-check:
    name: Build & Twine check (hatchling)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Build distributions
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine check dist/*
