# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to PyPI or PyPI Test

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    outputs:
      prerelease: ${{ steps.flag.outputs.pre }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify tag matches package version
        id: version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          TAG="${TAG#v}"
          PYVER=$(python - <<'PY'
          import pathlib, re
          text = pathlib.Path('src/sawmil/__init__.py').read_text()
          m = re.search(r"__version__\s*=\s*['\"]([^'\"]+)['\"]", text)
          print(m.group(1))
          PY)
          echo "Tag: $TAG"
          echo "Pkg: $PYVER"
          test "$TAG" = "$PYVER"

      - name: Install build tools
        run: python -m pip install -U build

      - name: Build release distributions
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Flag prerelease
        id: flag
        run: |
          echo "pre=${{ github.event.release.prerelease }}" >> "$GITHUB_OUTPUT"

  publish-testpypi:
    runs-on: ubuntu-latest
    needs: [release-build]
    if: needs.release-build.outputs.prerelease == 'true'
    permissions:
      id-token: write
      contents: read
    environment:
      name: testpypi
      url: https://test.pypi.org/project/sawmil/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to TestPyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          print-hash: true

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [release-build]
    if: needs.release-build.outputs.prerelease == 'false'
    permissions:
      id-token: write
      contents: read
    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      url: https://pypi.org/project/sawmil/
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
